"""
Quality Checks DAG — DataFlow EU

Runs Great Expectations suites against Bronze, Silver, and Gold layers
after the transformation_pipeline completes for the same logical date.

Schedule: daily at 09:00 UTC (1 hour after transformation)
Dependency: waits for transformation_pipeline via ExternalTaskSensor

On failure: Slack alert with the specific suite and expectation that failed,
so the on-call person doesn't need to dig through Airflow logs.
"""

from __future__ import annotations

import os
from datetime import datetime, timedelta

from airflow.decorators import dag, task
from airflow.sensors.external_task import ExternalTaskSensor

default_args = {
    "owner": "dataflow-eu",
    "retries": 1,
    "retry_delay": timedelta(minutes=10),
    "email_on_failure": False,
}


def _slack_alert(context: dict) -> None:
    webhook_url = os.environ.get("SLACK_WEBHOOK_URL")
    if not webhook_url:
        return
    import requests
    ti = context["task_instance"]
    requests.post(
        webhook_url,
        json={
            "text": (
                f":warning: *DataFlow EU — Data Quality Check Failed*\n"
                f"*Task:* `{ti.task_id}`\n"
                f"*Date:* `{context['execution_date']}`\n"
                f"*Log:* {ti.log_url}\n"
                f"Check the HTML report at docs/data-quality/index.html for details."
            )
        },
        timeout=10,
    )


def _run_quality_checks(layer: str) -> dict:
    """Run the GE runner script for a given layer and parse the result."""
    import subprocess
    import structlog

    log = structlog.get_logger("quality_pipeline")

    cmd = [
        "python", "/opt/airflow/scripts/run_quality_checks.py",
        "--layer", layer,
    ]

    log.info("quality_check_started", layer=layer)
    result = subprocess.run(cmd, capture_output=True, text=True)

    log.info(
        "quality_check_finished",
        layer=layer,
        returncode=result.returncode,
        stdout_tail=result.stdout[-1000:],
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"Quality checks failed for layer={layer}:\n{result.stdout[-2000:]}"
        )

    return {"layer": layer, "status": "passed"}


@dag(
    dag_id="quality_pipeline",
    description="Run Great Expectations suites against Bronze, Silver, and Gold layers",
    start_date=datetime(2019, 1, 1),
    schedule_interval="0 9 1 * *",  # 1st of every month at 09:00 UTC
    catchup=True,
    max_active_runs=1,
    default_args=default_args,
    on_failure_callback=_slack_alert,
    tags=["quality", "great-expectations"],
)
def quality_pipeline():

    wait_for_transformation = ExternalTaskSensor(
        task_id="wait_for_transformation",
        external_dag_id="transformation_pipeline",
        external_task_id="summarize_transformation",
        allowed_states=["success"],
        failed_states=["failed", "upstream_failed"],
        execution_delta=timedelta(hours=1),
        timeout=3600,
        poke_interval=60,
        mode="reschedule",
    )

    @task(task_id="check_bronze_quality")
    def check_bronze_quality() -> dict:
        return _run_quality_checks("bronze")

    @task(task_id="check_silver_quality")
    def check_silver_quality() -> dict:
        return _run_quality_checks("silver")

    @task(task_id="check_gold_quality")
    def check_gold_quality() -> dict:
        return _run_quality_checks("gold")

    @task(task_id="publish_data_docs")
    def publish_data_docs(bronze: dict, silver: dict, gold: dict) -> None:
        """
        Data Docs HTML is already generated by run_quality_checks.py at
        docs/data-quality/index.html. This task just logs the final summary;
        in a cloud deployment this is where you'd push the HTML to S3 + CloudFront
        or a static site host.
        """
        import structlog
        structlog.get_logger("quality_pipeline").info(
            "data_docs_published",
            bronze=bronze,
            silver=silver,
            gold=gold,
            docs_path="docs/data-quality/index.html",
        )

    bronze = check_bronze_quality()
    silver = check_silver_quality()
    gold = check_gold_quality()
    publish = publish_data_docs(bronze, silver, gold)

    wait_for_transformation >> bronze >> silver >> gold >> publish


quality_pipeline()
